Regin=swr.cn-north-4.myhuaweicloud.com
Org=hfbbg4
AppName=longconn
Version=v0.2

all:
	docker build --build-arg TARGETARCH=amd64 --platform linux/amd64 -t ${Regin}/${Org}/${AppName}:${Version} --no-cache .

